FROM mysql:8.0

RUN mkdir -p /var/lib/mysql

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

ENV \
    MYSQL_DATABASE=todos \
    MYSQL_ROOT_PASSWORD=team1dockerada\
    MYSQL_DATABASE=todos

COPY healthcheck.sh /usr/local/bin/

HEALTHCHECK --interval=5s --timeout=10s --retries=3 \
    CMD /usr/local/bin/healthcheck.sh